### ISSUE TITLE
Tips to improve your code even more.

### ISSUE THREAD

**Issue by MahdiSohaily** [julzedz/Awesome-Books#2]
Hello dear,
we have carefully reviewed your solution and found it excellent, and well organized.
To highlight: 🎯 

- Good usage of HTML semantic elements.
- No Linters error.
- Good git flow control.

Also here are some tips that will help you to improve your code even more. ❤️

- To improve the for loop performance when we want to iterate over an array and we have to use the `arr.length`, it's a good practice to store the `arr.length` into a variable and use that variable in for loop condition. [see](https://github.com/julzedz/Awesome-Books/blob/plain-js/main.js#L20).
- Another method to filter an array and remove a specific item is to use the `filter` method, so we kindly recommend using the filter method as it is more appropriate.

**Comment by julzedz** [comment]
Done, thank you!
